#!/bin/bash

#SBATCH --job-name d2q9-bgk
#SBATCH --nodes 2
#SBATCH --ntasks-per-node 1
#SBATCH --gres=gpu:2
#SBATCH --time 00:00:30
#SBATCH --partition gpu_veryshort
#SBATCH --output d2q9-bgk.out

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

size="1024x1024"
args="input_$size.params obstacles_$size.dat"

#! Run the executable
mpirun -ppn 1 -env CUDA_VISIBLE_DEVICES 0 ./d2q9-bgk $args : -env CUDA_VISIBLE_DEVICES 1 ./d2q9-bgk $args
